// <auto-generated />
using System;
using AppSamourai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TpEni.Migrations
{
    [DbContext(typeof(SamouraiDbContext))]
    [Migration("20230823081242_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.Property<int>("TechniquesId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateursId")
                        .HasColumnType("integer");

                    b.HasKey("TechniquesId", "UtilisateursId");

                    b.HasIndex("UtilisateursId");

                    b.ToTable("ArtMartialSamourai");
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Degats")
                        .HasColumnType("double precision");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Model.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArtMartials");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Force")
                        .HasColumnType("integer");

                    b.Property<int?>("IdArme")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Force = 1490,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 3,
                            Force = 354,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 1914,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 5,
                            Force = 40,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 6,
                            Force = 253,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 7,
                            Force = 676,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 8,
                            Force = 1015,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 9,
                            Force = 1078,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 10,
                            Force = 849,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 11,
                            Force = 1528,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 283,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 13,
                            Force = 390,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1495,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 15,
                            Force = 1487,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 16,
                            Force = 1701,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 17,
                            Force = 250,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 18,
                            Force = 58,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 19,
                            Force = 759,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 20,
                            Force = 1532,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 21,
                            Force = 1912,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 22,
                            Force = 219,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 23,
                            Force = 183,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 24,
                            Force = 908,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 25,
                            Force = 300,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 26,
                            Force = 1238,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 1271,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 686,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 620,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 30,
                            Force = 1458,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 31,
                            Force = 996,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 32,
                            Force = 913,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 33,
                            Force = 1568,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 666,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 200,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 1112,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 37,
                            Force = 1704,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 38,
                            Force = 1334,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 39,
                            Force = 693,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 40,
                            Force = 1126,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1082,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 42,
                            Force = 96,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 43,
                            Force = 901,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 44,
                            Force = 1022,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 45,
                            Force = 281,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 46,
                            Force = 94,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 47,
                            Force = 1436,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1628,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 49,
                            Force = 1543,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1802,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 51,
                            Force = 377,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 52,
                            Force = 181,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1148,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 54,
                            Force = 835,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 55,
                            Force = 733,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 56,
                            Force = 17,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 57,
                            Force = 502,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 58,
                            Force = 1539,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 59,
                            Force = 1046,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 60,
                            Force = 287,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 61,
                            Force = 836,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 62,
                            Force = 540,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 63,
                            Force = 954,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 64,
                            Force = 1237,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 65,
                            Force = 1757,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 66,
                            Force = 88,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 67,
                            Force = 1235,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 68,
                            Force = 1003,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 327,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 70,
                            Force = 907,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 71,
                            Force = 239,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 72,
                            Force = 1882,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 73,
                            Force = 177,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 74,
                            Force = 1780,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 75,
                            Force = 1149,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 76,
                            Force = 1273,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 77,
                            Force = 1453,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 78,
                            Force = 337,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 79,
                            Force = 1236,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 80,
                            Force = 7,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 81,
                            Force = 536,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 82,
                            Force = 373,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 83,
                            Force = 878,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 84,
                            Force = 1664,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 85,
                            Force = 1295,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1499,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 87,
                            Force = 966,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 88,
                            Force = 1019,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 89,
                            Force = 294,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 90,
                            Force = 391,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 91,
                            Force = 636,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 92,
                            Force = 700,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 93,
                            Force = 379,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 94,
                            Force = 685,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 95,
                            Force = 945,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 477,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 97,
                            Force = 1581,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 98,
                            Force = 279,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 99,
                            Force = 1521,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 100,
                            Force = 796,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 101,
                            Force = 606,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 102,
                            Force = 924,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 103,
                            Force = 1590,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 104,
                            Force = 129,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 105,
                            Force = 104,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 660,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 107,
                            Force = 642,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 108,
                            Force = 1403,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 109,
                            Force = 847,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 110,
                            Force = 577,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 111,
                            Force = 1379,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 112,
                            Force = 1242,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1599,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 114,
                            Force = 1259,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1367,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 116,
                            Force = 33,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 117,
                            Force = 120,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1089,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 119,
                            Force = 1728,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1354,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 121,
                            Force = 343,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 122,
                            Force = 348,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 123,
                            Force = 411,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1082,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 125,
                            Force = 178,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 126,
                            Force = 795,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1001,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 128,
                            Force = 161,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 129,
                            Force = 517,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 130,
                            Force = 1275,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 131,
                            Force = 1379,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 132,
                            Force = 1719,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 133,
                            Force = 15,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 134,
                            Force = 170,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 135,
                            Force = 794,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 136,
                            Force = 382,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 137,
                            Force = 1930,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1459,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 139,
                            Force = 466,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1983,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 141,
                            Force = 1899,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 142,
                            Force = 1366,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 143,
                            Force = 565,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 144,
                            Force = 751,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 145,
                            Force = 1749,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 146,
                            Force = 844,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 147,
                            Force = 991,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 148,
                            Force = 1366,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 149,
                            Force = 1947,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 150,
                            Force = 98,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1426,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 152,
                            Force = 457,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1969,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 154,
                            Force = 688,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 155,
                            Force = 327,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 156,
                            Force = 845,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 157,
                            Force = 1235,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1949,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 159,
                            Force = 749,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 160,
                            Force = 386,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1658,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 162,
                            Force = 788,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 163,
                            Force = 513,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1388,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 165,
                            Force = 852,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 166,
                            Force = 1986,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1022,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 168,
                            Force = 49,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 169,
                            Force = 230,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 170,
                            Force = 51,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1463,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 172,
                            Force = 396,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 173,
                            Force = 552,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 174,
                            Force = 1376,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 175,
                            Force = 74,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1111,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 177,
                            Force = 299,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 178,
                            Force = 1053,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 98,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 180,
                            Force = 1772,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1468,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 182,
                            Force = 16,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 183,
                            Force = 830,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 184,
                            Force = 1299,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 185,
                            Force = 994,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 186,
                            Force = 725,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 187,
                            Force = 25,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1756,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 189,
                            Force = 854,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 190,
                            Force = 1384,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1978,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 192,
                            Force = 425,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 193,
                            Force = 995,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 194,
                            Force = 1730,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 195,
                            Force = 295,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 196,
                            Force = 1872,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 197,
                            Force = 315,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1916,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 1195,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1496,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 201,
                            Force = 1852,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 202,
                            Force = 967,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1388,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 204,
                            Force = 1405,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 205,
                            Force = 1723,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1589,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 207,
                            Force = 270,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 208,
                            Force = 309,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 209,
                            Force = 1155,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 210,
                            Force = 45,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 211,
                            Force = 76,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 212,
                            Force = 92,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 213,
                            Force = 84,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 214,
                            Force = 1461,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 215,
                            Force = 1998,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 216,
                            Force = 709,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 217,
                            Force = 169,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 218,
                            Force = 1807,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 219,
                            Force = 660,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 888,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 221,
                            Force = 776,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 222,
                            Force = 788,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 223,
                            Force = 1505,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 224,
                            Force = 1940,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 225,
                            Force = 866,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 226,
                            Force = 1727,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 227,
                            Force = 305,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 228,
                            Force = 1681,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 229,
                            Force = 368,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1958,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 231,
                            Force = 845,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 232,
                            Force = 1720,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 233,
                            Force = 1805,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 234,
                            Force = 594,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 235,
                            Force = 411,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 236,
                            Force = 779,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 237,
                            Force = 348,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 898,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 239,
                            Force = 654,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 1251,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 241,
                            Force = 795,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 242,
                            Force = 101,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1475,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 244,
                            Force = 1161,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1602,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 246,
                            Force = 1505,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 247,
                            Force = 740,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1527,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 249,
                            Force = 59,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 173,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1002,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 252,
                            Force = 958,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 253,
                            Force = 750,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 340,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 255,
                            Force = 480,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 256,
                            Force = 710,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 257,
                            Force = 248,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 258,
                            Force = 474,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 259,
                            Force = 313,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1280,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 261,
                            Force = 563,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 262,
                            Force = 1725,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 263,
                            Force = 943,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 264,
                            Force = 1586,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 265,
                            Force = 1643,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1347,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 267,
                            Force = 65,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 268,
                            Force = 740,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 269,
                            Force = 506,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1809,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1605,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 272,
                            Force = 764,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 273,
                            Force = 221,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1786,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1553,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 276,
                            Force = 775,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1912,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 278,
                            Force = 1972,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1607,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1834,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1645,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 282,
                            Force = 1596,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 283,
                            Force = 1887,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1614,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 285,
                            Force = 109,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 286,
                            Force = 396,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 287,
                            Force = 630,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 288,
                            Force = 945,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 289,
                            Force = 791,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 290,
                            Force = 1529,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 291,
                            Force = 301,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 292,
                            Force = 1156,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 293,
                            Force = 203,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1871,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 295,
                            Force = 1914,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 210,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1399,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 1858,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1373,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1794,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 301,
                            Force = 263,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1224,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 303,
                            Force = 836,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 304,
                            Force = 181,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1571,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 306,
                            Force = 1195,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 307,
                            Force = 306,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 308,
                            Force = 1581,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1406,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 310,
                            Force = 461,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 311,
                            Force = 1967,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 312,
                            Force = 17,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 313,
                            Force = 778,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 314,
                            Force = 296,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 315,
                            Force = 560,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1752,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1556,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 318,
                            Force = 1554,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 1669,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 1729,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 321,
                            Force = 1161,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.HasOne("BO.Model.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("TechniquesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.Model.Samourai", null)
                        .WithMany()
                        .HasForeignKey("UtilisateursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.HasOne("BO.Model.Samourai", "Utilisateur")
                        .WithOne("Arme")
                        .HasForeignKey("BO.Model.Arme", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
