// <auto-generated />
using System;
using AppSamourai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TpEni.Migrations
{
    [DbContext(typeof(SamouraiDbContext))]
    [Migration("20230822092113_Fixtures")]
    partial class Fixtures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Degats")
                        .HasColumnType("double precision");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Force")
                        .HasColumnType("integer");

                    b.Property<int?>("IdArme")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Force = 201,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 2,
                            Force = 597,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 3,
                            Force = 1602,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 1933,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 5,
                            Force = 537,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 6,
                            Force = 903,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 7,
                            Force = 1767,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 8,
                            Force = 1300,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 9,
                            Force = 1603,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 10,
                            Force = 296,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 11,
                            Force = 871,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 653,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1431,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1329,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 15,
                            Force = 1566,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 16,
                            Force = 1785,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 17,
                            Force = 17,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 18,
                            Force = 1319,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 19,
                            Force = 1458,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 20,
                            Force = 1707,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 21,
                            Force = 1971,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 22,
                            Force = 1812,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 23,
                            Force = 1004,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 24,
                            Force = 569,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 25,
                            Force = 222,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 26,
                            Force = 990,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 88,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 452,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 1536,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 30,
                            Force = 753,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 31,
                            Force = 1051,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 32,
                            Force = 1054,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 33,
                            Force = 403,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 1493,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 1211,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 989,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 37,
                            Force = 659,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 38,
                            Force = 770,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1390,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 40,
                            Force = 1973,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1733,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 42,
                            Force = 1632,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 43,
                            Force = 366,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 44,
                            Force = 1618,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 45,
                            Force = 95,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 46,
                            Force = 422,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 47,
                            Force = 1784,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1676,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 49,
                            Force = 414,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1936,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 51,
                            Force = 238,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 52,
                            Force = 1632,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1727,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 54,
                            Force = 1501,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 55,
                            Force = 379,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 56,
                            Force = 1087,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 57,
                            Force = 655,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 58,
                            Force = 1708,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 59,
                            Force = 1417,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 60,
                            Force = 563,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 61,
                            Force = 1794,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 62,
                            Force = 34,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 63,
                            Force = 1541,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 64,
                            Force = 1163,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 65,
                            Force = 1882,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 66,
                            Force = 1021,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 67,
                            Force = 1391,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 68,
                            Force = 1965,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 1128,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 70,
                            Force = 1191,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 71,
                            Force = 898,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 72,
                            Force = 1070,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 73,
                            Force = 1840,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 74,
                            Force = 174,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 75,
                            Force = 784,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 76,
                            Force = 291,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 77,
                            Force = 1281,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 78,
                            Force = 1745,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 79,
                            Force = 367,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 80,
                            Force = 684,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 81,
                            Force = 765,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 82,
                            Force = 1249,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 83,
                            Force = 530,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 84,
                            Force = 1947,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 85,
                            Force = 310,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1095,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 87,
                            Force = 507,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 88,
                            Force = 849,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 89,
                            Force = 1003,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 90,
                            Force = 610,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 91,
                            Force = 757,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 92,
                            Force = 960,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 93,
                            Force = 1660,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1485,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 95,
                            Force = 1730,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 1360,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 97,
                            Force = 1533,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 98,
                            Force = 689,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 99,
                            Force = 814,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 100,
                            Force = 782,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 101,
                            Force = 400,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 102,
                            Force = 993,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 103,
                            Force = 539,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 104,
                            Force = 745,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 105,
                            Force = 1105,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 1196,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1911,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 108,
                            Force = 1907,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1952,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 110,
                            Force = 1086,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 111,
                            Force = 1619,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 112,
                            Force = 689,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 113,
                            Force = 1628,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 114,
                            Force = 50,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 115,
                            Force = 551,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 116,
                            Force = 225,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 117,
                            Force = 809,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 118,
                            Force = 884,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 119,
                            Force = 913,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1978,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 121,
                            Force = 1299,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 122,
                            Force = 79,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 123,
                            Force = 890,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 124,
                            Force = 401,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 125,
                            Force = 255,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 126,
                            Force = 782,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1213,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 128,
                            Force = 1621,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 129,
                            Force = 930,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 130,
                            Force = 934,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 131,
                            Force = 1004,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 132,
                            Force = 1561,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 133,
                            Force = 894,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 134,
                            Force = 1672,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 135,
                            Force = 1772,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 136,
                            Force = 520,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 137,
                            Force = 1987,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 138,
                            Force = 970,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 139,
                            Force = 186,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1905,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 141,
                            Force = 1071,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 142,
                            Force = 1208,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1526,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 144,
                            Force = 217,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 145,
                            Force = 215,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 146,
                            Force = 280,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 147,
                            Force = 302,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 148,
                            Force = 1813,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 149,
                            Force = 1726,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 150,
                            Force = 571,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 151,
                            Force = 787,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 152,
                            Force = 1108,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1093,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 154,
                            Force = 219,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 155,
                            Force = 464,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 156,
                            Force = 1281,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 157,
                            Force = 1933,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 158,
                            Force = 226,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 159,
                            Force = 100,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 160,
                            Force = 1159,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1265,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 162,
                            Force = 500,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1820,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1078,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 165,
                            Force = 1959,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 166,
                            Force = 220,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 167,
                            Force = 27,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 168,
                            Force = 745,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 169,
                            Force = 498,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 170,
                            Force = 774,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1227,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 172,
                            Force = 961,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1650,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 174,
                            Force = 435,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1891,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1042,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 177,
                            Force = 1611,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 178,
                            Force = 1717,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 1642,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 180,
                            Force = 1518,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1392,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1429,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 183,
                            Force = 194,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 184,
                            Force = 445,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 185,
                            Force = 282,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 186,
                            Force = 1802,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 187,
                            Force = 185,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1313,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 189,
                            Force = 613,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 190,
                            Force = 160,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1256,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 192,
                            Force = 226,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 193,
                            Force = 1044,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 194,
                            Force = 867,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 195,
                            Force = 1164,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 196,
                            Force = 247,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 197,
                            Force = 590,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 198,
                            Force = 810,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 313,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1167,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 201,
                            Force = 880,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 202,
                            Force = 1122,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 203,
                            Force = 615,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 204,
                            Force = 177,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 205,
                            Force = 12,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1257,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 207,
                            Force = 748,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1266,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 209,
                            Force = 616,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 210,
                            Force = 1812,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 211,
                            Force = 814,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 212,
                            Force = 324,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 213,
                            Force = 148,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 214,
                            Force = 1025,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 215,
                            Force = 1187,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 216,
                            Force = 158,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 217,
                            Force = 964,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 218,
                            Force = 1250,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 219,
                            Force = 878,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 1287,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 221,
                            Force = 1134,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1219,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 223,
                            Force = 1080,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 224,
                            Force = 774,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 225,
                            Force = 892,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 226,
                            Force = 669,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 227,
                            Force = 1417,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 228,
                            Force = 1468,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 229,
                            Force = 1039,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1478,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 231,
                            Force = 317,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 232,
                            Force = 398,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 233,
                            Force = 240,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1841,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 235,
                            Force = 479,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 236,
                            Force = 1425,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1277,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1244,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1032,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 36,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 241,
                            Force = 1202,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 242,
                            Force = 66,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1434,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 244,
                            Force = 204,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1116,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 246,
                            Force = 578,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 247,
                            Force = 552,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1299,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1517,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 179,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1365,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 252,
                            Force = 1692,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1459,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 191,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 255,
                            Force = 325,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 256,
                            Force = 1655,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1511,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1802,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 259,
                            Force = 914,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1256,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 261,
                            Force = 475,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 262,
                            Force = 1174,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 263,
                            Force = 1480,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 264,
                            Force = 606,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 265,
                            Force = 1128,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 266,
                            Force = 286,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 267,
                            Force = 244,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 268,
                            Force = 954,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 269,
                            Force = 1976,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 270,
                            Force = 299,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1885,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1389,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 273,
                            Force = 658,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1197,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 275,
                            Force = 435,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 276,
                            Force = 1607,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1468,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 278,
                            Force = 110,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1641,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1357,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 281,
                            Force = 161,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 282,
                            Force = 958,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 283,
                            Force = 1634,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1813,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 285,
                            Force = 1153,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1389,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 287,
                            Force = 956,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1896,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 289,
                            Force = 1063,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 290,
                            Force = 781,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 291,
                            Force = 1766,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 292,
                            Force = 1827,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 293,
                            Force = 149,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 294,
                            Force = 287,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 295,
                            Force = 101,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 1713,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1541,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 735,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 1885,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1895,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 301,
                            Force = 841,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 302,
                            Force = 539,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 303,
                            Force = 1874,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 304,
                            Force = 1845,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 305,
                            Force = 540,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 306,
                            Force = 332,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 307,
                            Force = 1919,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 308,
                            Force = 1629,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 309,
                            Force = 960,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 310,
                            Force = 789,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 311,
                            Force = 1518,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 312,
                            Force = 1539,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 313,
                            Force = 1591,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 314,
                            Force = 747,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1468,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 316,
                            Force = 414,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 317,
                            Force = 112,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 318,
                            Force = 885,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 1934,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 72,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.HasOne("BO.Model.Samourai", "Utilisateur")
                        .WithOne("Arme")
                        .HasForeignKey("BO.Model.Arme", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
