// <auto-generated />
using System;
using AppSamourai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TpEni.Migrations
{
    [DbContext(typeof(SamouraiDbContext))]
    [Migration("20230821145201_DeleteSamourai")]
    partial class DeleteSamourai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Degats")
                        .HasColumnType("double precision");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Force")
                        .HasColumnType("integer");

                    b.Property<int?>("IdArme")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Samourai");
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.HasOne("BO.Model.Samourai", "Utilisateur")
                        .WithOne("Arme")
                        .HasForeignKey("BO.Model.Arme", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
