// <auto-generated />
using System;
using AppSamourai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TpEni.Migrations
{
    [DbContext(typeof(SamouraiDbContext))]
    [Migration("20230822145557_ArtsMartiaux")]
    partial class ArtsMartiaux
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.Property<int>("TechniquesId")
                        .HasColumnType("integer");

                    b.Property<int>("UtilisateursId")
                        .HasColumnType("integer");

                    b.HasKey("TechniquesId", "UtilisateursId");

                    b.HasIndex("UtilisateursId");

                    b.ToTable("ArtMartialSamourai");
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Degats")
                        .HasColumnType("double precision");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Model.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ArtMartial");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Force")
                        .HasColumnType("integer");

                    b.Property<int?>("IdArme")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Force = 728,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 3,
                            Force = 285,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 88,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 5,
                            Force = 382,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 6,
                            Force = 899,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 7,
                            Force = 1560,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 8,
                            Force = 59,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 9,
                            Force = 632,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 10,
                            Force = 536,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 11,
                            Force = 415,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 860,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 13,
                            Force = 270,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1794,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 15,
                            Force = 1060,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 16,
                            Force = 635,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 17,
                            Force = 1939,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 18,
                            Force = 1164,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 19,
                            Force = 1522,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 20,
                            Force = 245,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 21,
                            Force = 1799,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 22,
                            Force = 1105,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 23,
                            Force = 595,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 24,
                            Force = 1336,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 25,
                            Force = 1785,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 26,
                            Force = 1518,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 487,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 1874,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 1280,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 30,
                            Force = 480,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 31,
                            Force = 1956,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 32,
                            Force = 540,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 33,
                            Force = 727,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 1465,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 1554,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 778,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 37,
                            Force = 521,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 38,
                            Force = 1608,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 39,
                            Force = 449,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 40,
                            Force = 1460,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1982,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 42,
                            Force = 167,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 43,
                            Force = 1759,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 44,
                            Force = 959,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 45,
                            Force = 1863,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 46,
                            Force = 1701,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 47,
                            Force = 411,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1495,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 49,
                            Force = 417,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 50,
                            Force = 1412,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 51,
                            Force = 1911,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 52,
                            Force = 1171,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1244,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 54,
                            Force = 382,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 55,
                            Force = 1096,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 56,
                            Force = 903,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 57,
                            Force = 1782,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 58,
                            Force = 307,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 59,
                            Force = 754,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 60,
                            Force = 1024,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 61,
                            Force = 1397,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 62,
                            Force = 1351,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 63,
                            Force = 1546,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 64,
                            Force = 277,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 65,
                            Force = 1514,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 66,
                            Force = 1626,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 67,
                            Force = 1120,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 68,
                            Force = 31,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 913,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 70,
                            Force = 1932,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 71,
                            Force = 1202,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 72,
                            Force = 824,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 73,
                            Force = 1615,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 74,
                            Force = 662,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 75,
                            Force = 947,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 76,
                            Force = 235,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 77,
                            Force = 4,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 78,
                            Force = 1228,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 79,
                            Force = 1104,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 80,
                            Force = 50,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 81,
                            Force = 1342,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 82,
                            Force = 1746,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 83,
                            Force = 120,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 84,
                            Force = 1048,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 85,
                            Force = 436,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1056,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 87,
                            Force = 1763,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 88,
                            Force = 10,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 89,
                            Force = 1785,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 90,
                            Force = 1780,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 91,
                            Force = 654,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 92,
                            Force = 757,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 93,
                            Force = 1846,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1751,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 95,
                            Force = 770,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 577,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 97,
                            Force = 714,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 98,
                            Force = 1386,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 99,
                            Force = 585,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 100,
                            Force = 890,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1346,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 102,
                            Force = 717,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 103,
                            Force = 338,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1598,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 105,
                            Force = 479,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 1393,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 107,
                            Force = 61,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 108,
                            Force = 634,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1538,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 110,
                            Force = 237,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 111,
                            Force = 993,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 112,
                            Force = 990,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 113,
                            Force = 270,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 114,
                            Force = 1191,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 115,
                            Force = 1132,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 116,
                            Force = 920,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 117,
                            Force = 765,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1068,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 119,
                            Force = 87,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 120,
                            Force = 181,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 121,
                            Force = 1844,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 122,
                            Force = 1252,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 123,
                            Force = 1051,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1969,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 125,
                            Force = 1759,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 126,
                            Force = 204,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1899,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 128,
                            Force = 1850,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 129,
                            Force = 753,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 130,
                            Force = 606,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 131,
                            Force = 787,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 132,
                            Force = 20,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 133,
                            Force = 16,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 134,
                            Force = 721,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 135,
                            Force = 1280,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 136,
                            Force = 627,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 137,
                            Force = 18,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 138,
                            Force = 1994,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 139,
                            Force = 1429,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1920,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 141,
                            Force = 1980,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 142,
                            Force = 362,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 143,
                            Force = 402,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 144,
                            Force = 855,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 145,
                            Force = 1265,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 146,
                            Force = 264,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 147,
                            Force = 257,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 148,
                            Force = 980,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 149,
                            Force = 811,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 150,
                            Force = 1342,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 151,
                            Force = 1232,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 152,
                            Force = 217,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 153,
                            Force = 43,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 154,
                            Force = 1596,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 155,
                            Force = 1901,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 156,
                            Force = 1365,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 157,
                            Force = 332,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 158,
                            Force = 337,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 159,
                            Force = 1184,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 160,
                            Force = 1563,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 161,
                            Force = 731,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 162,
                            Force = 1317,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 163,
                            Force = 748,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 164,
                            Force = 1930,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 165,
                            Force = 1754,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 166,
                            Force = 1979,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1547,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 168,
                            Force = 1445,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 169,
                            Force = 901,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1538,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1968,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 172,
                            Force = 1043,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1352,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 174,
                            Force = 1604,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 175,
                            Force = 1905,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 176,
                            Force = 1563,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 177,
                            Force = 983,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 178,
                            Force = 1015,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 418,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 180,
                            Force = 343,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 181,
                            Force = 180,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1337,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 183,
                            Force = 270,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 184,
                            Force = 38,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 185,
                            Force = 724,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 186,
                            Force = 1037,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 187,
                            Force = 1548,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1125,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 189,
                            Force = 1202,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 190,
                            Force = 1451,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1817,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 192,
                            Force = 1449,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 193,
                            Force = 31,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 194,
                            Force = 1744,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 195,
                            Force = 904,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 196,
                            Force = 1738,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 197,
                            Force = 1312,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 198,
                            Force = 994,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 507,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1520,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 201,
                            Force = 1257,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 202,
                            Force = 1997,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1721,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 204,
                            Force = 177,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 205,
                            Force = 1268,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1400,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 207,
                            Force = 1885,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1357,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 209,
                            Force = 1,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 210,
                            Force = 702,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1724,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 212,
                            Force = 805,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 213,
                            Force = 1260,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 214,
                            Force = 1152,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 215,
                            Force = 170,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 216,
                            Force = 625,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 217,
                            Force = 331,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 218,
                            Force = 930,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 219,
                            Force = 1289,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 6,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 221,
                            Force = 1862,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1054,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 223,
                            Force = 25,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 224,
                            Force = 114,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 225,
                            Force = 1997,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 226,
                            Force = 72,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 227,
                            Force = 192,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 228,
                            Force = 217,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 229,
                            Force = 331,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 230,
                            Force = 878,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 231,
                            Force = 56,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 232,
                            Force = 1193,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 233,
                            Force = 425,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1713,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 235,
                            Force = 804,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 236,
                            Force = 320,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1046,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1991,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 239,
                            Force = 326,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 1702,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 241,
                            Force = 1641,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 242,
                            Force = 366,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 243,
                            Force = 1093,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 244,
                            Force = 1783,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1777,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 246,
                            Force = 1731,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 247,
                            Force = 1206,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 248,
                            Force = 228,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1720,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 1500,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 251,
                            Force = 267,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 252,
                            Force = 1122,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1282,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1741,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1133,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 256,
                            Force = 18,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1966,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 258,
                            Force = 122,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 259,
                            Force = 1842,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 260,
                            Force = 421,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1874,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 262,
                            Force = 650,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 263,
                            Force = 558,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 264,
                            Force = 551,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 265,
                            Force = 305,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1693,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 267,
                            Force = 201,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 268,
                            Force = 76,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 269,
                            Force = 732,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 270,
                            Force = 356,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 271,
                            Force = 613,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1275,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 273,
                            Force = 1424,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 274,
                            Force = 119,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1332,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 276,
                            Force = 438,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 277,
                            Force = 1938,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 278,
                            Force = 895,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 279,
                            Force = 960,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 280,
                            Force = 444,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 281,
                            Force = 272,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 282,
                            Force = 805,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 283,
                            Force = 267,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1304,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 285,
                            Force = 1805,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 286,
                            Force = 760,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1712,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 288,
                            Force = 551,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 289,
                            Force = 1674,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 290,
                            Force = 104,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 291,
                            Force = 1489,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 292,
                            Force = 1198,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1641,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1824,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 295,
                            Force = 1494,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 1597,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 297,
                            Force = 816,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 1729,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 709,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1183,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 301,
                            Force = 1266,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 302,
                            Force = 488,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 303,
                            Force = 645,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 304,
                            Force = 1039,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 305,
                            Force = 177,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 306,
                            Force = 1810,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 307,
                            Force = 367,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 308,
                            Force = 1720,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 309,
                            Force = 380,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 310,
                            Force = 1825,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 311,
                            Force = 1497,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 312,
                            Force = 1275,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 313,
                            Force = 1252,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 314,
                            Force = 1448,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1763,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 316,
                            Force = 891,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 317,
                            Force = 408,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 318,
                            Force = 1972,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 918,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 1315,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 321,
                            Force = 1535,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("ArtMartialSamourai", b =>
                {
                    b.HasOne("BO.Model.ArtMartial", null)
                        .WithMany()
                        .HasForeignKey("TechniquesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.Model.Samourai", null)
                        .WithMany()
                        .HasForeignKey("UtilisateursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.HasOne("BO.Model.Samourai", "Utilisateur")
                        .WithOne("Arme")
                        .HasForeignKey("BO.Model.Arme", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
