// <auto-generated />
using System;
using AppSamourai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TpEni.Migrations
{
    [DbContext(typeof(SamouraiDbContext))]
    [Migration("20230823084007_ImprovedMappingArtMartial")]
    partial class ImprovedMappingArtMartial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Degats")
                        .HasColumnType("double precision");

                    b.Property<int?>("IdUtilisateur")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdUtilisateur")
                        .IsUnique();

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Model.ArtMartial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("ArtMartials");
                });

            modelBuilder.Entity("BO.Model.ArtMartialSamourai", b =>
                {
                    b.Property<int>("ArtMartialId")
                        .HasColumnType("integer");

                    b.Property<int>("SamouraiId")
                        .HasColumnType("integer");

                    b.Property<int>("ArtMartialsId")
                        .HasColumnType("integer");

                    b.Property<int>("SamouraisId")
                        .HasColumnType("integer");

                    b.HasKey("ArtMartialId", "SamouraiId");

                    b.HasIndex("SamouraiId");

                    b.ToTable("ArtMartialSamourais");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Force")
                        .HasColumnType("integer");

                    b.Property<int?>("IdArme")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Force = 495,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 3,
                            Force = 1156,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 680,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 5,
                            Force = 1765,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 6,
                            Force = 595,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 7,
                            Force = 835,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 8,
                            Force = 1191,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 9,
                            Force = 779,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 10,
                            Force = 214,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 11,
                            Force = 817,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 1617,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1306,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1694,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 15,
                            Force = 1600,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 16,
                            Force = 111,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 17,
                            Force = 398,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 18,
                            Force = 112,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 19,
                            Force = 1718,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 20,
                            Force = 1287,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 21,
                            Force = 1807,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 22,
                            Force = 84,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 23,
                            Force = 737,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 24,
                            Force = 1186,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 25,
                            Force = 571,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 26,
                            Force = 387,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 536,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 1414,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 874,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 30,
                            Force = 911,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 31,
                            Force = 1057,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 32,
                            Force = 932,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 33,
                            Force = 652,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 513,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 1187,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 1529,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 37,
                            Force = 283,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 38,
                            Force = 116,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1729,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 40,
                            Force = 606,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1685,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 42,
                            Force = 1706,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 43,
                            Force = 565,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 44,
                            Force = 101,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 45,
                            Force = 1211,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 46,
                            Force = 1859,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 47,
                            Force = 159,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1881,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 49,
                            Force = 1646,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 50,
                            Force = 856,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 51,
                            Force = 628,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 52,
                            Force = 1774,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 53,
                            Force = 968,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 54,
                            Force = 838,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 55,
                            Force = 578,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 56,
                            Force = 1437,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 57,
                            Force = 1230,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 58,
                            Force = 328,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 59,
                            Force = 1934,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 60,
                            Force = 425,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 61,
                            Force = 1871,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 62,
                            Force = 723,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 63,
                            Force = 533,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 64,
                            Force = 235,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 65,
                            Force = 1129,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 66,
                            Force = 1046,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 67,
                            Force = 291,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 68,
                            Force = 922,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 640,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 70,
                            Force = 649,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 71,
                            Force = 1413,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 72,
                            Force = 206,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 73,
                            Force = 996,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 74,
                            Force = 862,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 75,
                            Force = 1163,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 76,
                            Force = 646,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 77,
                            Force = 1614,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 78,
                            Force = 572,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 79,
                            Force = 1140,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 80,
                            Force = 871,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 81,
                            Force = 471,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 82,
                            Force = 115,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 83,
                            Force = 1087,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 84,
                            Force = 1575,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 85,
                            Force = 271,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 987,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 87,
                            Force = 1186,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 88,
                            Force = 763,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 89,
                            Force = 1513,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 90,
                            Force = 1622,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 91,
                            Force = 798,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 92,
                            Force = 1040,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 93,
                            Force = 24,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1918,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 95,
                            Force = 1254,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 441,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 97,
                            Force = 130,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 98,
                            Force = 29,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 99,
                            Force = 1580,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 100,
                            Force = 118,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1775,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 102,
                            Force = 252,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 103,
                            Force = 172,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 104,
                            Force = 507,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 105,
                            Force = 304,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 466,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 107,
                            Force = 1378,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 108,
                            Force = 1478,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 109,
                            Force = 1153,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 110,
                            Force = 950,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 111,
                            Force = 1035,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 112,
                            Force = 1164,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 113,
                            Force = 564,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 114,
                            Force = 417,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 115,
                            Force = 383,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 116,
                            Force = 374,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 117,
                            Force = 368,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1294,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 119,
                            Force = 179,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1433,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 121,
                            Force = 1162,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 122,
                            Force = 203,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 123,
                            Force = 1796,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 124,
                            Force = 992,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 125,
                            Force = 1733,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 126,
                            Force = 668,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 127,
                            Force = 121,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 128,
                            Force = 585,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 129,
                            Force = 1223,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 130,
                            Force = 1435,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 131,
                            Force = 1564,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 132,
                            Force = 175,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 133,
                            Force = 1564,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 134,
                            Force = 1763,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 135,
                            Force = 620,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 136,
                            Force = 1061,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 137,
                            Force = 1600,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 138,
                            Force = 620,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 139,
                            Force = 634,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 140,
                            Force = 10,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 141,
                            Force = 446,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 142,
                            Force = 632,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1463,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1738,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 145,
                            Force = 815,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 146,
                            Force = 627,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 147,
                            Force = 276,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 148,
                            Force = 729,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 149,
                            Force = 1544,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 150,
                            Force = 471,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 151,
                            Force = 72,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 152,
                            Force = 1450,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 153,
                            Force = 390,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 154,
                            Force = 642,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 155,
                            Force = 1997,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 156,
                            Force = 1447,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 157,
                            Force = 218,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 158,
                            Force = 409,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 159,
                            Force = 1448,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 160,
                            Force = 717,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1743,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 162,
                            Force = 1276,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 163,
                            Force = 747,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 164,
                            Force = 273,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 165,
                            Force = 849,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 166,
                            Force = 1909,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 167,
                            Force = 217,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 168,
                            Force = 886,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 169,
                            Force = 678,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1868,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1081,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 172,
                            Force = 1817,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 173,
                            Force = 352,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 174,
                            Force = 829,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 175,
                            Force = 697,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 176,
                            Force = 396,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 177,
                            Force = 583,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 178,
                            Force = 331,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 838,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 180,
                            Force = 189,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 181,
                            Force = 1559,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 182,
                            Force = 1646,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 183,
                            Force = 1077,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 184,
                            Force = 1510,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 185,
                            Force = 756,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 186,
                            Force = 1561,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 187,
                            Force = 622,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 188,
                            Force = 1786,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 189,
                            Force = 1895,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 190,
                            Force = 593,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1187,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 192,
                            Force = 1044,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 193,
                            Force = 1162,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 194,
                            Force = 515,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 195,
                            Force = 496,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 196,
                            Force = 1953,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 197,
                            Force = 1565,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 198,
                            Force = 1885,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 86,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 200,
                            Force = 1512,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 201,
                            Force = 849,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 202,
                            Force = 1958,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1465,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 204,
                            Force = 1379,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 205,
                            Force = 7,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 1390,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 207,
                            Force = 1052,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 208,
                            Force = 44,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 209,
                            Force = 191,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 210,
                            Force = 1250,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1654,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1974,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 213,
                            Force = 914,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 214,
                            Force = 1036,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 215,
                            Force = 1596,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 216,
                            Force = 1629,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 217,
                            Force = 1681,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 218,
                            Force = 940,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 219,
                            Force = 109,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 113,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 221,
                            Force = 803,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 222,
                            Force = 80,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 223,
                            Force = 1556,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 224,
                            Force = 1744,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 225,
                            Force = 1962,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 226,
                            Force = 400,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 227,
                            Force = 823,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 228,
                            Force = 1622,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 229,
                            Force = 1123,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1629,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 231,
                            Force = 1596,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 232,
                            Force = 561,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 233,
                            Force = 1806,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1549,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 235,
                            Force = 652,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 236,
                            Force = 1744,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 237,
                            Force = 465,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 865,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 239,
                            Force = 18,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 1504,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 241,
                            Force = 589,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 242,
                            Force = 1322,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 243,
                            Force = 609,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 244,
                            Force = 64,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1386,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 246,
                            Force = 33,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 247,
                            Force = 1191,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1567,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1736,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 1690,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 251,
                            Force = 1013,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 252,
                            Force = 1473,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1038,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1452,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1740,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 256,
                            Force = 93,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 257,
                            Force = 614,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 258,
                            Force = 547,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 259,
                            Force = 302,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1192,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 261,
                            Force = 495,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 262,
                            Force = 1048,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 263,
                            Force = 1805,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 264,
                            Force = 1966,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 265,
                            Force = 695,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1568,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 267,
                            Force = 1588,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 268,
                            Force = 1475,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 269,
                            Force = 1683,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 270,
                            Force = 1322,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 272,
                            Force = 1595,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 273,
                            Force = 759,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1297,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1110,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 276,
                            Force = 49,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 277,
                            Force = 176,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 278,
                            Force = 893,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 279,
                            Force = 1598,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1025,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 281,
                            Force = 364,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 282,
                            Force = 1828,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 283,
                            Force = 622,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 284,
                            Force = 1875,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 285,
                            Force = 1450,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 286,
                            Force = 1586,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1688,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 288,
                            Force = 207,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 289,
                            Force = 1205,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 290,
                            Force = 805,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 291,
                            Force = 1912,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 292,
                            Force = 497,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1190,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1182,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 295,
                            Force = 327,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 1316,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 297,
                            Force = 295,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 1771,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 999,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1650,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 301,
                            Force = 910,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1257,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 303,
                            Force = 1019,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 304,
                            Force = 1007,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 305,
                            Force = 1924,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 306,
                            Force = 1831,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 307,
                            Force = 925,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 308,
                            Force = 1114,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1711,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 310,
                            Force = 247,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 311,
                            Force = 676,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 312,
                            Force = 774,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 313,
                            Force = 315,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 314,
                            Force = 1372,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1298,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1913,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 317,
                            Force = 224,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 318,
                            Force = 837,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 1390,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 1390,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 321,
                            Force = 1479,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.HasOne("BO.Model.Samourai", "Utilisateur")
                        .WithOne("Arme")
                        .HasForeignKey("BO.Model.Arme", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("BO.Model.ArtMartialSamourai", b =>
                {
                    b.HasOne("BO.Model.ArtMartial", "ArtMartial")
                        .WithMany()
                        .HasForeignKey("ArtMartialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BO.Model.Samourai", "Samourai")
                        .WithMany()
                        .HasForeignKey("SamouraiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArtMartial");

                    b.Navigation("Samourai");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Navigation("Arme");
                });
#pragma warning restore 612, 618
        }
    }
}
