// <auto-generated />
using System;
using AppSamourai.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TpEni.Migrations
{
    [DbContext(typeof(SamouraiDbContext))]
    partial class SamouraiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Degats")
                        .HasColumnType("double precision");

                    b.Property<int?>("IdUtilisateur")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Armes");
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Force")
                        .HasColumnType("integer");

                    b.Property<int?>("IdArme")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("IdArme")
                        .IsUnique();

                    b.ToTable("Samourai");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Force = 1889,
                            Nom = "Abe Masakatsu"
                        },
                        new
                        {
                            Id = 3,
                            Force = 783,
                            Nom = "Adachi Yasumori"
                        },
                        new
                        {
                            Id = 4,
                            Force = 531,
                            Nom = "Adachi Kagemori"
                        },
                        new
                        {
                            Id = 5,
                            Force = 1124,
                            Nom = "Adams William"
                        },
                        new
                        {
                            Id = 6,
                            Force = 1415,
                            Nom = "Aiou Mototsuna"
                        },
                        new
                        {
                            Id = 7,
                            Force = 925,
                            Nom = "Akai Terukage"
                        },
                        new
                        {
                            Id = 8,
                            Force = 3,
                            Nom = "Akao Kiyotsuna"
                        },
                        new
                        {
                            Id = 9,
                            Force = 94,
                            Nom = "Akechi Mitsuhide"
                        },
                        new
                        {
                            Id = 10,
                            Force = 213,
                            Nom = "Akiyama Nobutomo"
                        },
                        new
                        {
                            Id = 11,
                            Force = 1894,
                            Nom = "Amago Haruhisa"
                        },
                        new
                        {
                            Id = 12,
                            Force = 1354,
                            Nom = "Amago Yoshihisa"
                        },
                        new
                        {
                            Id = 13,
                            Force = 1002,
                            Nom = "Andō Morinari"
                        },
                        new
                        {
                            Id = 14,
                            Force = 1908,
                            Nom = "Ankokuji Ekei"
                        },
                        new
                        {
                            Id = 15,
                            Force = 1430,
                            Nom = "Aochi Shigetsuna"
                        },
                        new
                        {
                            Id = 16,
                            Force = 1588,
                            Nom = "Aokage Takaakira"
                        },
                        new
                        {
                            Id = 17,
                            Force = 1824,
                            Nom = "Aoki Kazushige"
                        },
                        new
                        {
                            Id = 18,
                            Force = 779,
                            Nom = "Akahori Chohichi"
                        },
                        new
                        {
                            Id = 19,
                            Force = 756,
                            Nom = "Arai Hakuseki"
                        },
                        new
                        {
                            Id = 20,
                            Force = 823,
                            Nom = "Araki Motokiyo"
                        },
                        new
                        {
                            Id = 21,
                            Force = 1474,
                            Nom = "Araki Murashige"
                        },
                        new
                        {
                            Id = 22,
                            Force = 1140,
                            Nom = "Araki Muratsugu"
                        },
                        new
                        {
                            Id = 23,
                            Force = 208,
                            Nom = "Arima Kihei"
                        },
                        new
                        {
                            Id = 24,
                            Force = 612,
                            Nom = "Asakura Yoshikage"
                        },
                        new
                        {
                            Id = 25,
                            Force = 1264,
                            Nom = "Ayame Kagekatsu"
                        },
                        new
                        {
                            Id = 26,
                            Force = 630,
                            Nom = "Azai Hisamasa"
                        },
                        new
                        {
                            Id = 27,
                            Force = 274,
                            Nom = "Azai Nagamasa"
                        },
                        new
                        {
                            Id = 28,
                            Force = 1787,
                            Nom = "Azai Sukemasa"
                        },
                        new
                        {
                            Id = 29,
                            Force = 636,
                            Nom = "Baba Nobufusa"
                        },
                        new
                        {
                            Id = 30,
                            Force = 8,
                            Nom = "Bessho Nagaharu"
                        },
                        new
                        {
                            Id = 31,
                            Force = 38,
                            Nom = "Chacha"
                        },
                        new
                        {
                            Id = 32,
                            Force = 217,
                            Nom = "Chiba Shusaku Narimasa"
                        },
                        new
                        {
                            Id = 33,
                            Force = 734,
                            Nom = "Chōsokabe Morichika"
                        },
                        new
                        {
                            Id = 34,
                            Force = 1815,
                            Nom = "Chōsokabe Kunichika"
                        },
                        new
                        {
                            Id = 35,
                            Force = 121,
                            Nom = "Chōsokabe Motochika"
                        },
                        new
                        {
                            Id = 36,
                            Force = 48,
                            Nom = "Chōsokabe Nobuchika"
                        },
                        new
                        {
                            Id = 37,
                            Force = 373,
                            Nom = "Collache Eugène"
                        },
                        new
                        {
                            Id = 38,
                            Force = 49,
                            Nom = "Date Masamune"
                        },
                        new
                        {
                            Id = 39,
                            Force = 1432,
                            Nom = "Date Shigezane"
                        },
                        new
                        {
                            Id = 40,
                            Force = 719,
                            Nom = "Doi Toshikatsu"
                        },
                        new
                        {
                            Id = 41,
                            Force = 1769,
                            Nom = "Etō Shinpei"
                        },
                        new
                        {
                            Id = 42,
                            Force = 1290,
                            Nom = "Endō Naotsune"
                        },
                        new
                        {
                            Id = 43,
                            Force = 1668,
                            Nom = "Enjoji Nobutane"
                        },
                        new
                        {
                            Id = 44,
                            Force = 1129,
                            Nom = "Enomoto Takeaki"
                        },
                        new
                        {
                            Id = 45,
                            Force = 1100,
                            Nom = "Era Fusahide"
                        },
                        new
                        {
                            Id = 46,
                            Force = 1914,
                            Nom = "Fūma Kotarō"
                        },
                        new
                        {
                            Id = 47,
                            Force = 1082,
                            Nom = "Fuwa Mitsuharu"
                        },
                        new
                        {
                            Id = 48,
                            Force = 1574,
                            Nom = "Fukushima Masanori"
                        },
                        new
                        {
                            Id = 49,
                            Force = 623,
                            Nom = "Gamō Katahide"
                        },
                        new
                        {
                            Id = 50,
                            Force = 600,
                            Nom = "Gamō Ujisato"
                        },
                        new
                        {
                            Id = 51,
                            Force = 1394,
                            Nom = "Harada Naomasa"
                        },
                        new
                        {
                            Id = 52,
                            Force = 572,
                            Nom = "Harada Nobutane"
                        },
                        new
                        {
                            Id = 53,
                            Force = 1119,
                            Nom = "Harada Sanosuke"
                        },
                        new
                        {
                            Id = 54,
                            Force = 746,
                            Nom = "Hasekura Tsunenaga"
                        },
                        new
                        {
                            Id = 55,
                            Force = 1557,
                            Nom = "Hattori Hanzō"
                        },
                        new
                        {
                            Id = 56,
                            Force = 758,
                            Nom = "Hatano Hideharu"
                        },
                        new
                        {
                            Id = 57,
                            Force = 452,
                            Nom = "Hasegawa Eishin"
                        },
                        new
                        {
                            Id = 58,
                            Force = 713,
                            Nom = "Hayashizaki Jinsuke Shigenobu"
                        },
                        new
                        {
                            Id = 59,
                            Force = 1528,
                            Nom = "Hayashi Narinaga"
                        },
                        new
                        {
                            Id = 60,
                            Force = 206,
                            Nom = "Hijikata Toshizo"
                        },
                        new
                        {
                            Id = 61,
                            Force = 236,
                            Nom = "Hirate Masahide"
                        },
                        new
                        {
                            Id = 62,
                            Force = 1800,
                            Nom = "Hitotsubashi Keiki"
                        },
                        new
                        {
                            Id = 63,
                            Force = 770,
                            Nom = "Hōjō Masako"
                        },
                        new
                        {
                            Id = 64,
                            Force = 508,
                            Nom = "Hōjō Tokimune"
                        },
                        new
                        {
                            Id = 65,
                            Force = 1706,
                            Nom = "Hōjō Ujiyasu"
                        },
                        new
                        {
                            Id = 66,
                            Force = 622,
                            Nom = "Hōjō Ujimasa"
                        },
                        new
                        {
                            Id = 67,
                            Force = 608,
                            Nom = "Honda Tadakatsu"
                        },
                        new
                        {
                            Id = 68,
                            Force = 874,
                            Nom = "Honda Tadatomo"
                        },
                        new
                        {
                            Id = 69,
                            Force = 1785,
                            Nom = "Honganji Kennyo"
                        },
                        new
                        {
                            Id = 70,
                            Force = 530,
                            Nom = "Horio Yoshiharu"
                        },
                        new
                        {
                            Id = 71,
                            Force = 846,
                            Nom = "Hosokawa Fujitaka"
                        },
                        new
                        {
                            Id = 72,
                            Force = 234,
                            Nom = "Hosokawa Gracia"
                        },
                        new
                        {
                            Id = 73,
                            Force = 30,
                            Nom = "Hosokawa Tadaoki"
                        },
                        new
                        {
                            Id = 74,
                            Force = 305,
                            Nom = "Hotta Masatoshi"
                        },
                        new
                        {
                            Id = 75,
                            Force = 1097,
                            Nom = "Ii Naoaki"
                        },
                        new
                        {
                            Id = 76,
                            Force = 818,
                            Nom = "Ii Naomasa"
                        },
                        new
                        {
                            Id = 77,
                            Force = 1756,
                            Nom = "Ii Naomori"
                        },
                        new
                        {
                            Id = 78,
                            Force = 986,
                            Nom = "Ii Naonaka"
                        },
                        new
                        {
                            Id = 79,
                            Force = 912,
                            Nom = "Ii Naosuke"
                        },
                        new
                        {
                            Id = 80,
                            Force = 492,
                            Nom = "Ii Naotaka"
                        },
                        new
                        {
                            Id = 81,
                            Force = 1408,
                            Nom = "Ii Naotora"
                        },
                        new
                        {
                            Id = 82,
                            Force = 1893,
                            Nom = "Ii Naoyuki"
                        },
                        new
                        {
                            Id = 83,
                            Force = 1003,
                            Nom = "Ii Naozumi"
                        },
                        new
                        {
                            Id = 84,
                            Force = 195,
                            Nom = "Iizasa Ienao"
                        },
                        new
                        {
                            Id = 85,
                            Force = 1744,
                            Nom = "Ijuin Tadaaki"
                        },
                        new
                        {
                            Id = 86,
                            Force = 1886,
                            Nom = "Ikeda Tsuneoki"
                        },
                        new
                        {
                            Id = 87,
                            Force = 784,
                            Nom = "Imagawa Ujizane"
                        },
                        new
                        {
                            Id = 88,
                            Force = 421,
                            Nom = "Imagawa Yoshimoto"
                        },
                        new
                        {
                            Id = 89,
                            Force = 409,
                            Nom = "Imai Kanehira"
                        },
                        new
                        {
                            Id = 90,
                            Force = 1585,
                            Nom = "Inaba Yoshimichi"
                        },
                        new
                        {
                            Id = 91,
                            Force = 173,
                            Nom = "Inugami Nagayasu"
                        },
                        new
                        {
                            Id = 92,
                            Force = 1596,
                            Nom = "Ishida Mitsunari"
                        },
                        new
                        {
                            Id = 93,
                            Force = 187,
                            Nom = "Isshiki Fujinaga"
                        },
                        new
                        {
                            Id = 94,
                            Force = 1745,
                            Nom = "Itagaki Nobukata"
                        },
                        new
                        {
                            Id = 95,
                            Force = 1312,
                            Nom = "Itō Hirobumi"
                        },
                        new
                        {
                            Id = 96,
                            Force = 1088,
                            Nom = "Iwanari Tomomichi"
                        },
                        new
                        {
                            Id = 97,
                            Force = 424,
                            Nom = "Jinbo Nagamoto"
                        },
                        new
                        {
                            Id = 98,
                            Force = 459,
                            Nom = "Jonas Tönse"
                        },
                        new
                        {
                            Id = 99,
                            Force = 1404,
                            Nom = "Kannan Kumar(Salem)"
                        },
                        new
                        {
                            Id = 100,
                            Force = 981,
                            Nom = "Kakeda Toshimune"
                        },
                        new
                        {
                            Id = 101,
                            Force = 1671,
                            Nom = "Kaneko Ietada"
                        },
                        new
                        {
                            Id = 102,
                            Force = 1098,
                            Nom = "Katagiri Katsumoto"
                        },
                        new
                        {
                            Id = 103,
                            Force = 1703,
                            Nom = "Katakura Kojūro"
                        },
                        new
                        {
                            Id = 104,
                            Force = 1051,
                            Nom = "Katakura Shigenaga"
                        },
                        new
                        {
                            Id = 105,
                            Force = 1038,
                            Nom = "Kataoka Mitsumasa"
                        },
                        new
                        {
                            Id = 106,
                            Force = 1605,
                            Nom = "Katō Kiyomasa"
                        },
                        new
                        {
                            Id = 107,
                            Force = 101,
                            Nom = "Kawakami Gensai"
                        },
                        new
                        {
                            Id = 108,
                            Force = 180,
                            Nom = "Kido Takayoshi"
                        },
                        new
                        {
                            Id = 109,
                            Force = 771,
                            Nom = "Kikkawa Hiroie"
                        },
                        new
                        {
                            Id = 110,
                            Force = 1273,
                            Nom = "Kimotsuki Kanetsugu"
                        },
                        new
                        {
                            Id = 111,
                            Force = 1081,
                            Nom = "Kitamura Kansuke"
                        },
                        new
                        {
                            Id = 112,
                            Force = 101,
                            Nom = "Kobayakawa Hideaki"
                        },
                        new
                        {
                            Id = 113,
                            Force = 417,
                            Nom = "Kobayakawa Hidekane"
                        },
                        new
                        {
                            Id = 114,
                            Force = 784,
                            Nom = "Kobayakawa Takakage"
                        },
                        new
                        {
                            Id = 115,
                            Force = 72,
                            Nom = "Konishi Yukinaga"
                        },
                        new
                        {
                            Id = 116,
                            Force = 1476,
                            Nom = "Kojima Toyoharu"
                        },
                        new
                        {
                            Id = 117,
                            Force = 457,
                            Nom = "Kuroda Kanbei"
                        },
                        new
                        {
                            Id = 118,
                            Force = 1066,
                            Nom = "Kuroda Kiyotaka"
                        },
                        new
                        {
                            Id = 119,
                            Force = 1924,
                            Nom = "Kusunoki Masashige"
                        },
                        new
                        {
                            Id = 120,
                            Force = 1717,
                            Nom = "Kuwana Tarozaemon"
                        },
                        new
                        {
                            Id = 121,
                            Force = 78,
                            Nom = "Kumagai Naozane"
                        },
                        new
                        {
                            Id = 122,
                            Force = 986,
                            Nom = "Maeda Keiji"
                        },
                        new
                        {
                            Id = 123,
                            Force = 541,
                            Nom = "Maeda Matsu"
                        },
                        new
                        {
                            Id = 124,
                            Force = 1942,
                            Nom = "Maeda Nagatane"
                        },
                        new
                        {
                            Id = 125,
                            Force = 916,
                            Nom = "Maeda Toshiie"
                        },
                        new
                        {
                            Id = 126,
                            Force = 1619,
                            Nom = "Maeda Toshinaga"
                        },
                        new
                        {
                            Id = 127,
                            Force = 1530,
                            Nom = "Maeda Toshitsune"
                        },
                        new
                        {
                            Id = 128,
                            Force = 1341,
                            Nom = "Magome Kageyu"
                        },
                        new
                        {
                            Id = 129,
                            Force = 732,
                            Nom = "Manabe Akifusa"
                        },
                        new
                        {
                            Id = 130,
                            Force = 353,
                            Nom = "Matsudaira Katamori"
                        },
                        new
                        {
                            Id = 131,
                            Force = 997,
                            Nom = "Matsudaira Nobutsuna"
                        },
                        new
                        {
                            Id = 132,
                            Force = 259,
                            Nom = "Matsudaira Nobuyasu"
                        },
                        new
                        {
                            Id = 133,
                            Force = 1708,
                            Nom = "Matsudaira Higo no Kami Katamori"
                        },
                        new
                        {
                            Id = 134,
                            Force = 763,
                            Nom = "Matsudaira Sadanobu"
                        },
                        new
                        {
                            Id = 135,
                            Force = 1217,
                            Nom = "Matsudaira Tadayoshi"
                        },
                        new
                        {
                            Id = 136,
                            Force = 261,
                            Nom = "Matsudaira Teru"
                        },
                        new
                        {
                            Id = 137,
                            Force = 1894,
                            Nom = "Matsunaga Hisahide"
                        },
                        new
                        {
                            Id = 138,
                            Force = 15,
                            Nom = "Matsunaga Hisamichi"
                        },
                        new
                        {
                            Id = 139,
                            Force = 37,
                            Nom = "Matsuo Bashō"
                        },
                        new
                        {
                            Id = 140,
                            Force = 1236,
                            Nom = "Matsudaira Motoyasu"
                        },
                        new
                        {
                            Id = 141,
                            Force = 588,
                            Nom = "Minamoto no Mitsunaka"
                        },
                        new
                        {
                            Id = 142,
                            Force = 1856,
                            Nom = "Minamoto no Yoshiie"
                        },
                        new
                        {
                            Id = 143,
                            Force = 1803,
                            Nom = "Minamoto no Yoshimitsu"
                        },
                        new
                        {
                            Id = 144,
                            Force = 1146,
                            Nom = "Minamoto no Yoshinaka"
                        },
                        new
                        {
                            Id = 145,
                            Force = 823,
                            Nom = "Minamoto no Yoshitomo"
                        },
                        new
                        {
                            Id = 146,
                            Force = 1409,
                            Nom = "Minamoto no Yoshitsune"
                        },
                        new
                        {
                            Id = 147,
                            Force = 230,
                            Nom = "Minamoto no Tameyoshi"
                        },
                        new
                        {
                            Id = 148,
                            Force = 174,
                            Nom = "Minamoto no Yorimasa"
                        },
                        new
                        {
                            Id = 149,
                            Force = 856,
                            Nom = "Minamoto no Yorimitsu"
                        },
                        new
                        {
                            Id = 150,
                            Force = 0,
                            Nom = "Minamoto no Yoritomo"
                        },
                        new
                        {
                            Id = 151,
                            Force = 380,
                            Nom = "Minamoto no Noriyori"
                        },
                        new
                        {
                            Id = 152,
                            Force = 1650,
                            Nom = "Minoro Takashi"
                        },
                        new
                        {
                            Id = 153,
                            Force = 1892,
                            Nom = "Miura Anjin"
                        },
                        new
                        {
                            Id = 154,
                            Force = 1071,
                            Nom = "Miura Yoshimoto"
                        },
                        new
                        {
                            Id = 155,
                            Force = 209,
                            Nom = "Miyamoto Musashi"
                        },
                        new
                        {
                            Id = 156,
                            Force = 505,
                            Nom = "Miyoshi Chōkei"
                        },
                        new
                        {
                            Id = 157,
                            Force = 1941,
                            Nom = "Miyoshi Kazuhide"
                        },
                        new
                        {
                            Id = 158,
                            Force = 1556,
                            Nom = "Miyoshi Masaga"
                        },
                        new
                        {
                            Id = 159,
                            Force = 62,
                            Nom = "Miyoshi Masayasu"
                        },
                        new
                        {
                            Id = 160,
                            Force = 588,
                            Nom = "Miyoshi Moriyata"
                        },
                        new
                        {
                            Id = 161,
                            Force = 1605,
                            Nom = "Miyoshi Nagayuki"
                        },
                        new
                        {
                            Id = 162,
                            Force = 1406,
                            Nom = "Miyoshi Yoshitsugu"
                        },
                        new
                        {
                            Id = 163,
                            Force = 1471,
                            Nom = "Mizuno Tadakuni"
                        },
                        new
                        {
                            Id = 164,
                            Force = 264,
                            Nom = "Moniwa Yoshinao"
                        },
                        new
                        {
                            Id = 165,
                            Force = 1107,
                            Nom = "Mōri Motonari"
                        },
                        new
                        {
                            Id = 166,
                            Force = 752,
                            Nom = "Mōri Nagasada"
                        },
                        new
                        {
                            Id = 167,
                            Force = 1161,
                            Nom = "Mori Nagayoshi"
                        },
                        new
                        {
                            Id = 168,
                            Force = 489,
                            Nom = "Mōri Okimoto"
                        },
                        new
                        {
                            Id = 169,
                            Force = 1347,
                            Nom = "Mori Ranmaru"
                        },
                        new
                        {
                            Id = 170,
                            Force = 1995,
                            Nom = "Mōri Takamoto"
                        },
                        new
                        {
                            Id = 171,
                            Force = 1993,
                            Nom = "Mori Tadamasa"
                        },
                        new
                        {
                            Id = 172,
                            Force = 679,
                            Nom = "Mōri Terumoto"
                        },
                        new
                        {
                            Id = 173,
                            Force = 1274,
                            Nom = "Mori Yoshinari"
                        },
                        new
                        {
                            Id = 174,
                            Force = 1921,
                            Nom = "Murai Sadakatsu"
                        },
                        new
                        {
                            Id = 175,
                            Force = 365,
                            Nom = "Nagakura Shinpachi"
                        },
                        new
                        {
                            Id = 176,
                            Force = 560,
                            Nom = "Nagao Harukage"
                        },
                        new
                        {
                            Id = 177,
                            Force = 1884,
                            Nom = "Nagao Kagenobu"
                        },
                        new
                        {
                            Id = 178,
                            Force = 302,
                            Nom = "Nagao Masakage"
                        },
                        new
                        {
                            Id = 179,
                            Force = 951,
                            Nom = "Nagao Tamekage"
                        },
                        new
                        {
                            Id = 180,
                            Force = 110,
                            Nom = "Nakagawa Kiyohide"
                        },
                        new
                        {
                            Id = 181,
                            Force = 943,
                            Nom = "Nakaoka Shintarō"
                        },
                        new
                        {
                            Id = 182,
                            Force = 128,
                            Nom = "Naoe Kagetsuna"
                        },
                        new
                        {
                            Id = 183,
                            Force = 262,
                            Nom = "Naoe Kanetsugu"
                        },
                        new
                        {
                            Id = 184,
                            Force = 184,
                            Nom = "Narita Kaihime"
                        },
                        new
                        {
                            Id = 185,
                            Force = 543,
                            Nom = "Nene"
                        },
                        new
                        {
                            Id = 186,
                            Force = 230,
                            Nom = "Nihonmatsu Yoshitsugu"
                        },
                        new
                        {
                            Id = 187,
                            Force = 1515,
                            Nom = "Niimi Nishiki"
                        },
                        new
                        {
                            Id = 188,
                            Force = 606,
                            Nom = "Niiro Tadamoto"
                        },
                        new
                        {
                            Id = 189,
                            Force = 984,
                            Nom = "Niwa Nagahide"
                        },
                        new
                        {
                            Id = 190,
                            Force = 217,
                            Nom = "Niwa Nagashige"
                        },
                        new
                        {
                            Id = 191,
                            Force = 1401,
                            Nom = "Oda Hiroyoshi"
                        },
                        new
                        {
                            Id = 192,
                            Force = 351,
                            Nom = "Oda Nobuhide"
                        },
                        new
                        {
                            Id = 193,
                            Force = 869,
                            Nom = "Oda Nobukata"
                        },
                        new
                        {
                            Id = 194,
                            Force = 1267,
                            Nom = "Oda Nobukiyo"
                        },
                        new
                        {
                            Id = 195,
                            Force = 1270,
                            Nom = "Oda Nobunaga"
                        },
                        new
                        {
                            Id = 196,
                            Force = 186,
                            Nom = "Oda Nobutada"
                        },
                        new
                        {
                            Id = 197,
                            Force = 969,
                            Nom = "Oda Nobutomo"
                        },
                        new
                        {
                            Id = 198,
                            Force = 995,
                            Nom = "Oda Nobukatsu"
                        },
                        new
                        {
                            Id = 199,
                            Force = 274,
                            Nom = "Oda Nobuyasu"
                        },
                        new
                        {
                            Id = 200,
                            Force = 547,
                            Nom = "Ogasawara Shōsai"
                        },
                        new
                        {
                            Id = 201,
                            Force = 1053,
                            Nom = "Ōishi Kuranosuke"
                        },
                        new
                        {
                            Id = 202,
                            Force = 781,
                            Nom = "Okada Izō"
                        },
                        new
                        {
                            Id = 203,
                            Force = 1026,
                            Nom = "Judge Ooka"
                        },
                        new
                        {
                            Id = 204,
                            Force = 1909,
                            Nom = "Ōta Dōkan"
                        },
                        new
                        {
                            Id = 205,
                            Force = 1573,
                            Nom = "Ōtani Yoshitsugu"
                        },
                        new
                        {
                            Id = 206,
                            Force = 16,
                            Nom = "Ōtani Yoshiharu"
                        },
                        new
                        {
                            Id = 207,
                            Force = 1382,
                            Nom = "Ōtomo Sōrin"
                        },
                        new
                        {
                            Id = 208,
                            Force = 1477,
                            Nom = "Okita Sōji"
                        },
                        new
                        {
                            Id = 209,
                            Force = 270,
                            Nom = "Ōkubo Toshimichi"
                        },
                        new
                        {
                            Id = 210,
                            Force = 1567,
                            Nom = "Okunomiya Masaie"
                        },
                        new
                        {
                            Id = 211,
                            Force = 1181,
                            Nom = "Ōuchi Yoshitaka"
                        },
                        new
                        {
                            Id = 212,
                            Force = 1777,
                            Nom = "Omy Yoshika"
                        },
                        new
                        {
                            Id = 213,
                            Force = 1302,
                            Nom = "Pore Sufi"
                        },
                        new
                        {
                            Id = 214,
                            Force = 568,
                            Nom = "Reizei Takatoyo"
                        },
                        new
                        {
                            Id = 215,
                            Force = 751,
                            Nom = "Rokkaku Sadayori"
                        },
                        new
                        {
                            Id = 216,
                            Force = 477,
                            Nom = "Rokkaku Yoshiharu"
                        },
                        new
                        {
                            Id = 217,
                            Force = 63,
                            Nom = "Rokkaku Yoshikata"
                        },
                        new
                        {
                            Id = 218,
                            Force = 1275,
                            Nom = "Rusu Masakage"
                        },
                        new
                        {
                            Id = 219,
                            Force = 1897,
                            Nom = "Ryūzōji Takanobu"
                        },
                        new
                        {
                            Id = 220,
                            Force = 794,
                            Nom = "Saigo Kiyokazu"
                        },
                        new
                        {
                            Id = 221,
                            Force = 124,
                            Nom = "Saigō Masako"
                        },
                        new
                        {
                            Id = 222,
                            Force = 1780,
                            Nom = "Sagara Taketō"
                        },
                        new
                        {
                            Id = 223,
                            Force = 1482,
                            Nom = "Saigō Takamori"
                        },
                        new
                        {
                            Id = 224,
                            Force = 1818,
                            Nom = "Saigo Yoshikatsu"
                        },
                        new
                        {
                            Id = 225,
                            Force = 830,
                            Nom = "Saitō Dōsan"
                        },
                        new
                        {
                            Id = 226,
                            Force = 1338,
                            Nom = "Saitō Hajime"
                        },
                        new
                        {
                            Id = 227,
                            Force = 685,
                            Nom = "Saito Musashibō Benkei"
                        },
                        new
                        {
                            Id = 228,
                            Force = 1778,
                            Nom = "Saitō Yoshitatsu"
                        },
                        new
                        {
                            Id = 229,
                            Force = 810,
                            Nom = "Sakai Tadakiyo"
                        },
                        new
                        {
                            Id = 230,
                            Force = 1351,
                            Nom = "Sakai Tadashige"
                        },
                        new
                        {
                            Id = 231,
                            Force = 1496,
                            Nom = "Sakai Tadatsugu"
                        },
                        new
                        {
                            Id = 232,
                            Force = 1339,
                            Nom = "Sakai Tadayo"
                        },
                        new
                        {
                            Id = 233,
                            Force = 1209,
                            Nom = "Sakakibara Yasumasa"
                        },
                        new
                        {
                            Id = 234,
                            Force = 1684,
                            Nom = "Sakamoto Ryōma"
                        },
                        new
                        {
                            Id = 235,
                            Force = 63,
                            Nom = "Sakuma Morimasa"
                        },
                        new
                        {
                            Id = 236,
                            Force = 990,
                            Nom = "Sakuma Nobumori"
                        },
                        new
                        {
                            Id = 237,
                            Force = 1817,
                            Nom = "Sanada Akihime"
                        },
                        new
                        {
                            Id = 238,
                            Force = 1684,
                            Nom = "Sanada Komatsuhime"
                        },
                        new
                        {
                            Id = 239,
                            Force = 1008,
                            Nom = "Sanada Masayuki"
                        },
                        new
                        {
                            Id = 240,
                            Force = 1744,
                            Nom = "Sanada Nobuyuki"
                        },
                        new
                        {
                            Id = 241,
                            Force = 1453,
                            Nom = "Sanada Yukimura"
                        },
                        new
                        {
                            Id = 242,
                            Force = 1367,
                            Nom = "Sasaki Kojirō"
                        },
                        new
                        {
                            Id = 243,
                            Force = 593,
                            Nom = "Sassa Narimasa"
                        },
                        new
                        {
                            Id = 244,
                            Force = 1237,
                            Nom = "Sasuke Sarutobi"
                        },
                        new
                        {
                            Id = 245,
                            Force = 1523,
                            Nom = "Serizawa Kamo"
                        },
                        new
                        {
                            Id = 246,
                            Force = 886,
                            Nom = "Shibata Katsuie"
                        },
                        new
                        {
                            Id = 247,
                            Force = 1909,
                            Nom = "Shima Sakon"
                        },
                        new
                        {
                            Id = 248,
                            Force = 1509,
                            Nom = "Shimada Ichirō"
                        },
                        new
                        {
                            Id = 249,
                            Force = 1087,
                            Nom = "Shimazu Katsuhisa"
                        },
                        new
                        {
                            Id = 250,
                            Force = 1668,
                            Nom = "Shimazu Tadahisa"
                        },
                        new
                        {
                            Id = 251,
                            Force = 140,
                            Nom = "Shimazu Tadatsune"
                        },
                        new
                        {
                            Id = 252,
                            Force = 815,
                            Nom = "Shimazu Tadayoshi"
                        },
                        new
                        {
                            Id = 253,
                            Force = 1991,
                            Nom = "Shimazu Takahisa"
                        },
                        new
                        {
                            Id = 254,
                            Force = 1487,
                            Nom = "Shimazu Toyohisa"
                        },
                        new
                        {
                            Id = 255,
                            Force = 1980,
                            Nom = "Shimazu Yoshihiro"
                        },
                        new
                        {
                            Id = 256,
                            Force = 745,
                            Nom = "Shimazu Yoshihisa"
                        },
                        new
                        {
                            Id = 257,
                            Force = 1568,
                            Nom = "Shindou Hiroshii"
                        },
                        new
                        {
                            Id = 258,
                            Force = 1386,
                            Nom = "Sogo Nagayasu"
                        },
                        new
                        {
                            Id = 259,
                            Force = 763,
                            Nom = "Sue Yoshitaka"
                        },
                        new
                        {
                            Id = 260,
                            Force = 1149,
                            Nom = "Tachibana Muneshige"
                        },
                        new
                        {
                            Id = 261,
                            Force = 1291,
                            Nom = "Tachibana Dōsetsu"
                        },
                        new
                        {
                            Id = 262,
                            Force = 528,
                            Nom = "Tachibana Ginchiyo"
                        },
                        new
                        {
                            Id = 263,
                            Force = 670,
                            Nom = "Taigen Sessai"
                        },
                        new
                        {
                            Id = 264,
                            Force = 852,
                            Nom = "Taira no Kiyomori"
                        },
                        new
                        {
                            Id = 265,
                            Force = 860,
                            Nom = "Taira Masakado"
                        },
                        new
                        {
                            Id = 266,
                            Force = 1504,
                            Nom = "Takahashi Shigetane"
                        },
                        new
                        {
                            Id = 267,
                            Force = 489,
                            Nom = "Takenaka Shigeharu"
                        },
                        new
                        {
                            Id = 268,
                            Force = 860,
                            Nom = "Takasugi Shinsaku"
                        },
                        new
                        {
                            Id = 269,
                            Force = 1677,
                            Nom = "Takayama Justo"
                        },
                        new
                        {
                            Id = 270,
                            Force = 789,
                            Nom = "Takayama Ukon"
                        },
                        new
                        {
                            Id = 271,
                            Force = 1140,
                            Nom = "Takechi Hanpeita"
                        },
                        new
                        {
                            Id = 272,
                            Force = 850,
                            Nom = "Takeda Katsuyori"
                        },
                        new
                        {
                            Id = 273,
                            Force = 1840,
                            Nom = "Takeda Nobukatsu"
                        },
                        new
                        {
                            Id = 274,
                            Force = 1470,
                            Nom = "Takeda Nobushige"
                        },
                        new
                        {
                            Id = 275,
                            Force = 1677,
                            Nom = "Takeda Shingen"
                        },
                        new
                        {
                            Id = 276,
                            Force = 168,
                            Nom = "Takenaka Hanbei"
                        },
                        new
                        {
                            Id = 277,
                            Force = 29,
                            Nom = "Tani Tadasumi"
                        },
                        new
                        {
                            Id = 278,
                            Force = 174,
                            Nom = "Tōdō Takatora"
                        },
                        new
                        {
                            Id = 279,
                            Force = 835,
                            Nom = "Toki Yorinari"
                        },
                        new
                        {
                            Id = 280,
                            Force = 1953,
                            Nom = "Tochimitsu Gantyoki"
                        },
                        new
                        {
                            Id = 281,
                            Force = 1518,
                            Nom = "Tokugawa Ieyasu"
                        },
                        new
                        {
                            Id = 282,
                            Force = 1044,
                            Nom = "Tokugawa Hidetada"
                        },
                        new
                        {
                            Id = 283,
                            Force = 372,
                            Nom = "Tokugawa Nariaki"
                        },
                        new
                        {
                            Id = 284,
                            Force = 75,
                            Nom = "Tokugawa Yoshinobu"
                        },
                        new
                        {
                            Id = 285,
                            Force = 525,
                            Nom = "Torii Mototada"
                        },
                        new
                        {
                            Id = 286,
                            Force = 838,
                            Nom = "Toyotomi Hidenaga"
                        },
                        new
                        {
                            Id = 287,
                            Force = 1385,
                            Nom = "Toyotomi Hideyoshi"
                        },
                        new
                        {
                            Id = 288,
                            Force = 1899,
                            Nom = "Toyotomi Hideyori"
                        },
                        new
                        {
                            Id = 289,
                            Force = 1117,
                            Nom = "Tozuka Tadaharu"
                        },
                        new
                        {
                            Id = 290,
                            Force = 1261,
                            Nom = "Tsukahara Bokuden"
                        },
                        new
                        {
                            Id = 291,
                            Force = 1467,
                            Nom = "Uesugi Kagekatsu"
                        },
                        new
                        {
                            Id = 292,
                            Force = 695,
                            Nom = "Uesugi Kagetora"
                        },
                        new
                        {
                            Id = 293,
                            Force = 1707,
                            Nom = "Uesugi Kenshin"
                        },
                        new
                        {
                            Id = 294,
                            Force = 1422,
                            Nom = "Ujiie Naotomo"
                        },
                        new
                        {
                            Id = 295,
                            Force = 76,
                            Nom = "Ukita Naoie"
                        },
                        new
                        {
                            Id = 296,
                            Force = 633,
                            Nom = "Ukita Okiie"
                        },
                        new
                        {
                            Id = 297,
                            Force = 1883,
                            Nom = "Umezawa Michiharu"
                        },
                        new
                        {
                            Id = 298,
                            Force = 82,
                            Nom = "Usami Sadamitsu"
                        },
                        new
                        {
                            Id = 299,
                            Force = 330,
                            Nom = "Uyama Hisanobu"
                        },
                        new
                        {
                            Id = 300,
                            Force = 1380,
                            Nom = "Wada Shinsuke"
                        },
                        new
                        {
                            Id = 301,
                            Force = 1855,
                            Nom = "Watanabe Kazan"
                        },
                        new
                        {
                            Id = 302,
                            Force = 1790,
                            Nom = "Watanabe no Tsuna"
                        },
                        new
                        {
                            Id = 303,
                            Force = 820,
                            Nom = "Yasumero Kenshin"
                        },
                        new
                        {
                            Id = 304,
                            Force = 1608,
                            Nom = "Yagyū Jūbei Mitsuyoshi"
                        },
                        new
                        {
                            Id = 305,
                            Force = 745,
                            Nom = "Yagyū Munenori"
                        },
                        new
                        {
                            Id = 306,
                            Force = 1111,
                            Nom = "Yamauchi Kazutoyo"
                        },
                        new
                        {
                            Id = 307,
                            Force = 1000,
                            Nom = "Yamada Arinaga"
                        },
                        new
                        {
                            Id = 308,
                            Force = 396,
                            Nom = "Yamada Arinobu"
                        },
                        new
                        {
                            Id = 309,
                            Force = 1698,
                            Nom = "Yamada Nagamasa"
                        },
                        new
                        {
                            Id = 310,
                            Force = 1282,
                            Nom = "Yamagata Masakage"
                        },
                        new
                        {
                            Id = 311,
                            Force = 713,
                            Nom = "Yamakawa Hiroshi"
                        },
                        new
                        {
                            Id = 312,
                            Force = 1125,
                            Nom = "Yamakawa Kenjirō"
                        },
                        new
                        {
                            Id = 313,
                            Force = 532,
                            Nom = "Yamakawa Naoe"
                        },
                        new
                        {
                            Id = 314,
                            Force = 36,
                            Nom = "Yamanaka Yukimori"
                        },
                        new
                        {
                            Id = 315,
                            Force = 1054,
                            Nom = "Yamanami Keisuke"
                        },
                        new
                        {
                            Id = 316,
                            Force = 1731,
                            Nom = "Yamaoka Tesshū"
                        },
                        new
                        {
                            Id = 317,
                            Force = 1640,
                            Nom = "Yanagawa Kenzaburo"
                        },
                        new
                        {
                            Id = 318,
                            Force = 200,
                            Nom = "Yanagisawa Yoshiyasu"
                        },
                        new
                        {
                            Id = 319,
                            Force = 694,
                            Nom = "Yonekura Shigetsugu"
                        },
                        new
                        {
                            Id = 320,
                            Force = 778,
                            Nom = "Yūki Hideyasu"
                        },
                        new
                        {
                            Id = 321,
                            Force = 751,
                            Nom = "Yasuke"
                        });
                });

            modelBuilder.Entity("BO.Model.Samourai", b =>
                {
                    b.HasOne("BO.Model.Arme", "Arme")
                        .WithOne("Utilisateur")
                        .HasForeignKey("BO.Model.Samourai", "IdArme")
                        .HasPrincipalKey("BO.Model.Arme", "IdUtilisateur")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Arme");
                });

            modelBuilder.Entity("BO.Model.Arme", b =>
                {
                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
